<!-- Add Family Modal -->
<div class="modal fade" id="addFamilyModal" tabindex="-1" aria-labelledby="addFamilyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addFamilyModalLabel">Add New Family</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="../controllers/bhw_add_family.php" method="POST">
                    <!-- Household ID (Hidden, already known) -->
                    <input type="hidden" name="household_id" value="<?php echo htmlspecialchars($household_id); ?>" />

                    <!-- Family No. (Disabled, auto-generated) -->
                    <div class="mb-3">
                        <label for="family_no" class="form-label">Family No.</label>
                        <input type="text" class="form-control" id="family_no" name="family_no" value="Auto-generated" disabled>
                        <small class="form-text text-muted">This is automatically generated by the system.</small>
                    </div>

                    <!-- Parent Family (Optional) -->
                    <div class="mb-3">
                        <label for="parent_family" class="form-label">Parent Family</label>
                        <select class="form-control" id="parent_family" name="parent_family">
                            <option value="">None</option>
                            <?php foreach ($families as $family): ?>
                                <option value="<?php echo htmlspecialchars($family['family_id']); ?>">
                                    <?php 
                                    // Check if the family_name exists, if not show the family_id with a fallback message
                                    echo htmlspecialchars($family['family_name'] ?? 'No Family Name (Family No. ' . $family['family_id'] . ')');
                                    ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <!-- 4Ps Member -->
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="4PsMember" name="4PsMember">
                        <label class="form-check-label" for="4PsMember">4Ps Member</label>
                    </div>

                    <!-- Submit Button -->
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Add Family</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>